services:
  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    networks:
      - lognet

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.1
    container_name: opensearch-dashboards
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
    ports:
      - "5601:5601"
    networks:
      - lognet
    depends_on:
      - opensearch

  log-backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    networks:
      - lognet
    depends_on:
      - opensearch

  log-frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - lognet
    depends_on:
      - log-backend

networks:
  lognet:
